version: 0.2
run-as: root


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 522711436140.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=522711436140.dkr.ecr.ap-south-1.amazonaws.com/blog
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t blog .
      - docker tag blog:latest 522711436140.dkr.ecr.ap-south-1.amazonaws.com/blog:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 522711436140.dkr.ecr.ap-south-1.amazonaws.com/blog:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' app $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json