# This is a basic workflow to help you get started with Actions

name: Deploy to EBS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_run:
    workflows: ["Deploy to ECR"]
	types:
	  - completed


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            application_name: my-blog
            environment_name: Myblog-env-1
            version_label: 12345
            region: ap-south-1
            deployment_package: Dockerrun.aws.zip 
